steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Run tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test']

  # Deploy to Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'htmlToPdf'
      - '--runtime=nodejs16'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--entry-point=htmlToPdf'
      - '--memory=1024MB'
      - '--timeout=300s'
      - '--region=us-central1'